#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.lala2
#  SPDX-License-Identifier: Apache-2.0
#

name: Unit Tests, Deploy, Integration Test
on:
  push:
    branches:
      - develop
jobs:
  merge-develop-to-mainline:
    name: Merge develop to mainline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.request('PATCH /repos/{owner}/{repo}/git/refs/{ref}', {
              owner: 'carvantes',
              repo: 'fhir-works-on-aws-deployment',
              ref: 'heads/mainline',
              sha: context.sha
            });
            console.log(result);
