#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.lala2
#  SPDX-License-Identifier: Apache-2.0
#

name: Unit Tests, Deploy, Integration Test
on:
  push:
    branches:
      - develop
jobs:
  merge-develop-to-mainline:
    name: Merge develop to mainline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Merge to mainline
        uses: Embraser01/update-git-branch-action@v1.0.0
        with:
          branch: mainline
          githubToken: ${{ secrets.GITHUB_TOKEN }}
