#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.lala
#  SPDX-License-Identifier: Apache-2.0
#

name: Unit Tests, Deploy, Integration Test
on:
  push:
    branches:
      - develop
jobs:
  merge-develop-to-mainline:
    name: Merge develop to mainline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{secrets.MERGE_TOKEN}}
          fetch-depth: 0
      - name: Temporarily disable branch protection
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: carvantes
          repo: fhir-works-on-aws-deployment
          branch: mainline
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
      - name: Merge to mainline
        run: |
          git checkout mainline
          echo
          echo "  Attempting to merge the 'develop' branch ($(git log -1 --pretty=%H develop))"
          echo "  into the 'mainline' branch ($(git log -1 --pretty=%H mainline))"
          echo
          git merge --ff-only --no-edit develop
          git push origin mainline
      - name: Enable branch protection 
        uses: octokit/request-action@v2.x
        if: always() # Make sure to enable branch protection even if other steps fail
        with:
          route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: carvantes
          repo: fhir-works-on-aws-deployment
          branch: mainline
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
